# Generated by Django 3.2.7 on 2021-12-01 16:35

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import phonenumber_field.modelfields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name="Nom de l'organisation")),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('date_created', models.DateField(verbose_name='Date de création')),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='organization/logo')),
                ('cover_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='organization/cover_image')),
                ('address', models.TextField(verbose_name='Adresse de la rue')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('fax', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numéro de fax')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Numéro de téléphone')),
                ('extract', models.TextField(blank=True, max_length=300, null=True, verbose_name='Extrait')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenu')),
                ('status', models.CharField(choices=[('DR', 'Draft'), ('PB', 'Published')], default='DR', max_length=10, verbose_name="statut de l'organisation")),
                ('author', models.ForeignKey(blank=True, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ('-name',),
            },
        ),
    ]
